unused = "#485867"

[base16]
  black = "#485867"
  base01 = "#5a6d7a"
  base02 = "#6d828e"
  base03 = "#8299a1"
  base04 = "#98afb5"
  base05 = "#b0c5c8"
  base06 = "#c9dbdc"
  white = "#e3efef"
  red = "#b38686"
  orange  = "#d8bba2"
  yellow = "#aab386"
  green = "#87b386"
  cyan = "#86b3b3"
  blue = "#868cb3"
  purple = "#b386b2"
  brown = "#b39f9f"

[dark]
  button = ["base16.black","base16.base04"]
  button-focus = ["base16.white","base16.purple"]
  button-selected = ["base16.white","base16.base04"]
  cmdline = ["base16.black","base16.yellow"]
  cmdline-button = ["base16.yellow","base16.black"]
  cmdline-border = ["base16.black","base16.yellow"]
  copy-mode = ["base16.black","base16.yellow"]
  copy-mode-alt = ["base16.yellow","base16.black"]
  copy-mode-label = ["base16.white","base16.red"]
  current-capture = ["base16.white","themes.unused"]
  dialog = ["base16.black","base16.yellow"]
  dialog-button = ["base16.yellow","base16.black"]
  default = ["base16.white","base16.black"]
  filter-empty = ["base16.black","base16.cyan"]
  filter-intermediate = ["base16.black","base16.orange"]
  filter-invalid = ["base16.black","base16.red"]
  filter-menu = ["base16.white","base16.black"]
  filter-valid = ["base16.black","base16.green"]
  hex-byte-selected = ["base16.white","base16.purple"]
  hex-byte-unselected = ["base16.white","base16.black"]
  hex-field-selected = ["base16.black","base16.cyan"]
  hex-field-unselected = ["base16.black","base16.white"]
  hex-interval-selected = ["base16.white","base16.base03"]
  hex-interval-unselected = ["base16.white","base16.base02"]
  hex-layer-selected = ["base16.white","base16.base03"]
  hex-layer-unselected = ["base16.white","base16.base02"]
  packet-list-cell-focus = ["base16.white","base16.purple"]
  packet-list-cell-selected = ["base16.white","base16.base03"]
  packet-list-row-focus = ["base16.white","base16.cyan"]
  packet-list-row-selected = ["base16.white","base16.base02"]
  packet-struct-focus = ["base16.white","base16.cyan"]
  packet-struct-selected = ["base16.black","base16.base03"]
  progress-complete = ["base16.white","base16.purple"]
  progress-default = ["base16.white","base16.black"]
  progress-spinner = ["base16.yellow","base16.purple"]
  spinner = ["base16.yellow","base16.black"]
  stream-client = ["base16.black","base16.red"]
  stream-match = ["base16.black","base16.yellow"]
  stream-search = ["base16.black","base16.white"]
  stream-server = ["base16.black","base16.blue"]
  title = ["base16.red","unused"]

[light]
  button = ["base16.black","base16.white"]
  button-focus = ["base16.black","base16.purple"]
  button-selected = ["base16.black","base16.base04"]
  cmdline = ["base16.black","base16.yellow"]
  cmdline-button = ["base16.yellow","base16.black"]
  cmdline-border = ["base16.black","base16.yellow"]
  copy-mode = ["base16.white","base16.yellow"]
  copy-mode-alt = ["base16.yellow","base16.white"]
  copy-mode-label = ["base16.black","base16.red"]
  current-capture = ["base16.black","unused"]
  dialog = ["base16.black","base16.yellow"]
  dialog-button = ["base16.yellow","base16.black"]
  default = ["base16.black","base16.white"]
  filter-empty = ["base16.black","base16.cyan"]
  filter-intermediate = ["base16.black","base16.orange"]
  filter-invalid = ["base16.black","base16.red"]
  filter-menu = ["base16.black","base16.white"]
  filter-valid = ["base16.black","base16.green"]
  hex-byte-selected = ["base16.white","base16.purple"]
  hex-byte-unselected = ["base16.black","base16.white"]
  hex-field-selected = ["base16.black","base16.cyan"]
  hex-field-unselected = ["base16.black","base16.base03"]
  hex-interval-selected = ["base16.white","base16.base03"]
  hex-interval-unselected = ["base16.black","base16.base05"]
  hex-layer-selected = ["base16.white","base16.base03"]
  hex-layer-unselected = ["base16.black","base16.base05"]
  packet-list-cell-focus = ["base16.white","base16.purple"]
  packet-list-cell-selected = ["base16.black","base16.base04"]
  packet-list-row-focus = ["base16.white","base16.cyan"]
  packet-list-row-selected = ["base16.black","base16.base05"]
  packet-struct-focus = ["base16.white","base16.cyan"]
  packet-struct-selected = ["base16.black","base16.base05"]
  progress-complete = ["base16.white","base16.purple"]
  progress-default = ["base16.white","base16.black"]
  progress-spinner = ["base16.yellow","base16.black"]
  spinner = ["base16.yellow","base16.white"]
  stream-client = ["base16.white","base16.red"]
  stream-match = ["base16.white","base16.yellow"]
  stream-search = ["base16.white","base16.black"]
  stream-server = ["base16.white","base16.blue"]
  title = ["base16.red","unused"]
