unused = "#1c2128"

[base16]
  black = "#1c2128"
  base01 = "#373e47"
  base02 = "#444c56"
  base03 = "#545d68"
  base04 = "#768390"
  base05 = "#909dab"
  base06 = "#adbac7"
  white = "#cdd9e5"
  red = "#f47067"
  orange  = "#e0823d"
  yellow = "#c69026"
  green = "#57ab5a"
  cyan = "#96d0ff"
  blue = "#539bf5"
  purple = "#e275ad"
  brown = "#ae5622"

[dark]
  button = ["base16.black","base16.base04"]
  button-focus = ["base16.white","base16.purple"]
  button-selected = ["base16.white","base16.base04"]
  cmdline = ["base16.black","base16.yellow"]
  cmdline-button = ["base16.yellow","base16.black"]
  cmdline-border = ["base16.black","base16.yellow"]
  copy-mode = ["base16.black","base16.yellow"]
  copy-mode-alt = ["base16.yellow","base16.black"]
  copy-mode-label = ["base16.white","base16.red"]
  current-capture = ["base16.white","themes.unused"]
  dialog = ["base16.black","base16.yellow"]
  dialog-button = ["base16.yellow","base16.black"]
  default = ["base16.white","base16.black"]
  filter-empty = ["base16.black","base16.cyan"]
  filter-intermediate = ["base16.black","base16.orange"]
  filter-invalid = ["base16.black","base16.red"]
  filter-menu = ["base16.white","base16.black"]
  filter-valid = ["base16.black","base16.green"]
  hex-byte-selected = ["base16.white","base16.purple"]
  hex-byte-unselected = ["base16.white","base16.black"]
  hex-field-selected = ["base16.black","base16.cyan"]
  hex-field-unselected = ["base16.black","base16.white"]
  hex-interval-selected = ["base16.white","base16.base03"]
  hex-interval-unselected = ["base16.white","base16.base02"]
  hex-layer-selected = ["base16.white","base16.base03"]
  hex-layer-unselected = ["base16.white","base16.base02"]
  packet-list-cell-focus = ["base16.white","base16.purple"]
  packet-list-cell-selected = ["base16.white","base16.base03"]
  packet-list-row-focus = ["base16.white","base16.cyan"]
  packet-list-row-selected = ["base16.white","base16.base02"]
  packet-struct-focus = ["base16.white","base16.cyan"]
  packet-struct-selected = ["base16.black","base16.base03"]
  progress-complete = ["base16.white","base16.purple"]
  progress-default = ["base16.white","base16.black"]
  progress-spinner = ["base16.yellow","base16.purple"]
  spinner = ["base16.yellow","base16.black"]
  stream-client = ["base16.black","base16.red"]
  stream-match = ["base16.black","base16.yellow"]
  stream-search = ["base16.black","base16.white"]
  stream-server = ["base16.black","base16.blue"]
  title = ["base16.red","unused"]

[light]
  button = ["base16.black","base16.white"]
  button-focus = ["base16.black","base16.purple"]
  button-selected = ["base16.black","base16.base04"]
  cmdline = ["base16.black","base16.yellow"]
  cmdline-button = ["base16.yellow","base16.black"]
  cmdline-border = ["base16.black","base16.yellow"]
  copy-mode = ["base16.white","base16.yellow"]
  copy-mode-alt = ["base16.yellow","base16.white"]
  copy-mode-label = ["base16.black","base16.red"]
  current-capture = ["base16.black","unused"]
  dialog = ["base16.black","base16.yellow"]
  dialog-button = ["base16.yellow","base16.black"]
  default = ["base16.black","base16.white"]
  filter-empty = ["base16.black","base16.cyan"]
  filter-intermediate = ["base16.black","base16.orange"]
  filter-invalid = ["base16.black","base16.red"]
  filter-menu = ["base16.black","base16.white"]
  filter-valid = ["base16.black","base16.green"]
  hex-byte-selected = ["base16.white","base16.purple"]
  hex-byte-unselected = ["base16.black","base16.white"]
  hex-field-selected = ["base16.black","base16.cyan"]
  hex-field-unselected = ["base16.black","base16.base03"]
  hex-interval-selected = ["base16.white","base16.base03"]
  hex-interval-unselected = ["base16.black","base16.base05"]
  hex-layer-selected = ["base16.white","base16.base03"]
  hex-layer-unselected = ["base16.black","base16.base05"]
  packet-list-cell-focus = ["base16.white","base16.purple"]
  packet-list-cell-selected = ["base16.black","base16.base04"]
  packet-list-row-focus = ["base16.white","base16.cyan"]
  packet-list-row-selected = ["base16.black","base16.base05"]
  packet-struct-focus = ["base16.white","base16.cyan"]
  packet-struct-selected = ["base16.black","base16.base05"]
  progress-complete = ["base16.white","base16.purple"]
  progress-default = ["base16.white","base16.black"]
  progress-spinner = ["base16.yellow","base16.black"]
  spinner = ["base16.yellow","base16.white"]
  stream-client = ["base16.white","base16.red"]
  stream-match = ["base16.white","base16.yellow"]
  stream-search = ["base16.white","base16.black"]
  stream-server = ["base16.white","base16.blue"]
  title = ["base16.red","unused"]
